version: '3.1'

services:
  app:
    image: dst-joomla:php-7.4
    working_dir: ${WORKDIR_CONTAINER}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${PWD}${PROJECT_PATH}:${WORKDIR_CONTAINER}
      - ${PWD}${PHP_INI_PATH}:/usr/local/etc/php
      - ${PWD}${PHP_LOGS_PATH}:/var/log/apache2
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - db

  db:
    image: mysql:5
    container_name: ${CONTAINER_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ${PWD}${VOLUME_MIGRATIONS}:/docker-entrypoint-initdb.d
      - ${PWD}${VOLUME_CONF}:/etc/mysql/conf.d
      - ${PWD}${VOLUME_DATA}:/var/lib/mysql
      - ${PWD}${VOLUME_LOGS}:/var/log/mysql
      - ${PWD}${VOLUME_BACKUPS}:/backups

  adminer:
    image: adminer
    container_name: ${CONTAINER_NAME}_adminer
    restart: 'no'
    ports:
      - ${PORT_GESTOR}:8080
