version: '3.1'

services:
  app:
    image: pablo262/dst-joomla:php-7.4
    working_dir: ${PHP_WORKDIR_CONTAINER}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ${ROOT_PATH}${PHP_PROJECT_PATH}:${PHP_WORKDIR_CONTAINER}
      - ${ROOT_PATH}${PHP_VIRTUALHOST_PATH}:/usr/local/etc/php/000-default.conf
      - ${ROOT_PATH}${PHP_LOGS_PATH}:/var/log/apache2
    ports:
      - ${PHP_WEB_PORT}:80
    depends_on:
      - db

  db:
    image: mysql:5
    container_name: ${CONTAINER_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ${ROOT_PATH}${VOLUME_MIGRATIONS}:/docker-entrypoint-initdb.d
      - ${ROOT_PATH}${VOLUME_CONF}:/etc/mysql/conf.d
      - ${ROOT_PATH}${VOLUME_DATA}:/var/lib/mysql
      # - ${ROOT_PATH}${VOLUME_LOGS}:/var/log/mysql
      - ${ROOT_PATH}${VOLUME_BACKUPS}:/backups

  adminer:
    image: adminer
    container_name: ${CONTAINER_NAME}_adminer
    restart: 'no'
    ports:
      - ${PORT_GESTOR}:8080
