version: '3.8'

services:
  app:
    image: pablo262/php:8.2-apache
    working_dir: ${PHP_WORKDIR_CONTAINER}
    container_name: ${CONTAINER_NAME}
    environment:
      JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK: 1
    volumes:
      - ${ROOT_PATH}${PHP_PROJECT_PATH}:${PHP_WORKDIR_CONTAINER}
      - ${ROOT_PATH}${PHP_VIRTUALHOST_PATH}:/etc/apache2/sites-available
      # - ${ROOT_PATH}${PHP_LOGS_PATH}:/var/log/apache2
      - ${ROOT_PATH}${PHP_CMD_SCRIPTS_PATH}:/docker-cmd
    ports:
      - ${PHP_WEB_PORT}:80
    command: sh -c "chmod +x /docker-cmd/${PHP_CMD_MAIN_SCRIPT_FILE} && . /docker-cmd/${PHP_CMD_MAIN_SCRIPT_FILE} && apache2-foreground"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - ${ROOT_PATH}${VOLUME_MIGRATIONS}:/docker-entrypoint-initdb.d
      - ${ROOT_PATH}${VOLUME_CONF}:/etc/mysql/conf.d
      - ${ROOT_PATH}${VOLUME_DATA}:/var/lib/mysql
      # - ${ROOT_PATH}${VOLUME_LOGS}:/var/log/mysql
      - ${ROOT_PATH}${VOLUME_BACKUPS}:/backups

  adminer:
    image: adminer
    container_name: ${CONTAINER_NAME}_adminer
    restart: 'no'
    ports:
      - ${PORT_GESTOR}:8080
